### ISSUE TITLE
Feature request: ignore policy assignment

### ISSUE THREAD

**Issue by Tailzip** [Azure/policy-compliance-scan#20]
Hi,

We'd like to ignore a given policy assignment, is there a plan to add such feature in the future?

Our use case, along with our custom policies, we have _Azure Security Center_ built-in policy initiative which contains policies that are partially non-relevant for our needs.

We could have a new input that would look like this :

```yaml
steps:
  - name: Check for compliance
    uses: azure/policy-compliance-scan@v0
    with:
      scopes: |
        /subscriptions/xxxx-xxxx-xxxx-xxxx
      assignment-ignore: |
        /subscriptions/xxxx-xxxx-xxxx-xxxx/providers/Microsoft.Authorization/policyAssignments/SecurityCenterBuiltIn
```
