### ISSUE TITLE
Scope as variable

### ISSUE THREAD

**Issue by sbugalski** [Azure/policy-compliance-scan#29]
Hello,

I would like to ask if we can add scope as variable? 
So every time new subscription is created we automatically set it instead of modifying subscriptions.

**Comment by Josh-01** [comment]
Hi @sbugalski ,
Do you mean adding it as an environment variable and using it in the workflow as action input?

**Comment by sbugalski** [comment]
@Josh-01 - yes. So I could load subscriptions, instead of hardcoding them

**Comment by Josh-01** [comment]
Hi @sbugalski ,
Yes, you should be able to do that. If you mean something like the example below, it should work.

```
- name: Checking compliant resource
        uses: ./policy-compliance-scan
        with:
          scopes: |
            /subscriptions/${{env.POLICY_SUBSCRIPTION}}/resourcegroups/policy-compliant-rg
        id: complianceCheck
```

, where POLICY_SUBSCRIPTION is an env variable defined somewhere in the workflow before this step.
